Tom32iUserBundle_Twitter:
    resource: "@Tom32iUserBundle/Controller/TwitterController.php"
    type:     annotation
    prefix:   /twitter

Tom32iUserBundle_Confirmation:
    resource: "@Tom32iUserBundle/Controller/ConfirmationController.php"
    type:     annotation
    prefix:   /

Tom32iUserBundle_Registration:
    resource: "@Tom32iUserBundle/Controller/RegistrationController.php"
    type:     annotation
    prefix:   /

Tom32iUserBundle_Profile:
    resource: "@Tom32iUserBundle/Controller/ProfileController.php"
    type:     annotation
    prefix:   /

Tom32iUserBundle_Security:
    resource: "@Tom32iUserBundle/Controller/SecurityController.php"
    type:     annotation
    prefix:   /